
[[render]]
id = "mize-mmejs"
type = "render-view"
main = "public/main.json"

[[webcomponent]]
id = "mize-mmejs-mainfolder"
main = "public/main-folder.js"
webroot = "public"

[[webcomponent]]
id = "mize-mmejs-topbar"
main = "public/top-bar.js"
webroot = "public"
