
[[render]]
name = "mize-mmejs"
json = "public/main.json"

[[webcomponent]]
name = "mize-mmejs-mainfolder"
main = "public/main-folder.js"

[[webcomponent]]
name = "mize-mmejs-topbar"
main = "public/top-bar.js"
webroot = "public"
