
[[render]]
id = "mize-mmejs"
type = "render-view"
main = "public/main.json"

[[render]]
id = "mize-mmejs-mainfolder"
type = "webcomponent"
main = "public/main-folder.js"
webroot = "public"

[[render]]
id = "mize-mmejs-topbar"
type = "webcomponent"
main = "public/top-bar.js"
webroot = "public"
